### ISSUE TITLE
Error related to model caching.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#162]
I see this error when running the GA based test. It's not fatal to program execution, but I think that might be because None type models are filtered out.
```python 
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f427810b668>>
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxy_65hcd'
  File "/opt/conda/lib/python3.5/shutil.py", line 465, in rmtree
  File "/opt/conda/lib/python3.5/shutil.py", line 463, in rmtree
Exception ignored in: <finalize object at 0x7f42dec8c890; dead>
Traceback (most recent call last):
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxy_65hcd'
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f427810b668>>
    onerror(os.lstat, path, sys.exc_info())
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpsrqy23l9'
  File "/opt/conda/lib/python3.5/shutil.py", line 463, in rmtree
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f427810b668>>
Exception ignored in: <finalize object at 0x7f42dec8c890; dead>
Traceback (most recent call last):
    orig_st = os.lstat(path)
Traceback (most recent call last):
  File "/home/jovyan/neuronunit/neuronunit/models/__init__.py", line 193, in __del__
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpsrqy23l9'
  File "/opt/conda/lib/python3.5/weakref.py", line 519, in __call__
    super(LEMSModel,self).__del__()
AttributeError: 'super' object has no attribute '__del__'
    return info.func(*info.args, **(info.kwargs or {}))
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f42a1f105c0>>
  File "/opt/conda/lib/python3.5/tempfile.py", line 797, in _cleanup
Exception ignored in: <finalize object at 0x7f42dec8c890; dead>
Traceback (most recent call last):
Traceback (most recent call last):
    _shutil.rmtree(name)
  File "/home/jovyan/neuronunit/neuronunit/models/__init__.py", line 193, in __del__
  File "/opt/conda/lib/python3.5/shutil.py", line 465, in rmtree
  File "/opt/conda/lib/python3.5/tempfile.py", line 797, in _cleanup
  File "/opt/conda/lib/python3.5/weakref.py", line 519, in __call__
  File "/home/jovyan/neuronunit/neuronunit/models/__init__.py", line 193, in __del__
Traceback (most recent call last):
    onerror(os.lstat, path, sys.exc_info())
    super(LEMSModel,self).__del__()
  File "/opt/conda/lib/python3.5/shutil.py", line 463, in rmtree
    return info.func(*info.args, **(info.kwargs or {}))
    orig_st = os.lstat(path)
AttributeError: 'super' object has no attribute '__del__'
  File "/opt/conda/lib/python3.5/weakref.py", line 519, in __call__
    super(LEMSModel,self).__del__()
  File "/opt/conda/lib/python3.5/tempfile.py", line 797, in _cleanup
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxy_65hcd'
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f42780a8e48>>
Traceback (most recent call last):
    _shutil.rmtree(name)
  File "/home/jovyan/neuronunit/neuronunit/models/__init__.py", line 193, in __del__
    return info.func(*info.args, **(info.kwargs or {}))
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/shutil.py", line 465, in rmtree
    super(LEMSModel,self).__del__()
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f427810b668>>
  File "/opt/conda/lib/python3.5/tempfile.py", line 797, in _cleanup
    onerror(os.lstat, path, sys.exc_info())
  File "/home/jovyan/neuronunit/neuronunit/models/__init__.py", line 193, in __del__
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/shutil.py", line 463, in rmtree
    _shutil.rmtree(name)
    super(LEMSModel,self).__del__()
  File "/home/jovyan/neuronunit/neuronunit/models/__init__.py", line 193, in __del__
  File "/opt/conda/lib/python3.5/shutil.py", line 465, in rmtree
    orig_st = os.lstat(path)
    super(LEMSModel,self).__del__()
    onerror(os.lstat, path, sys.exc_info())
    _shutil.rmtree(name)
AttributeError: 'super' object has no attribute '__del__'
  File "/opt/conda/lib/python3.5/shutil.py", line 463, in rmtree
  File "/opt/conda/lib/python3.5/shutil.py", line 465, in rmtree
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f42a1f105c0>>
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f42a1f105c0>>
    orig_st = os.lstat(path)
AttributeError: 'super' object has no attribute '__del__'
AttributeError: 'super' object has no attribute '__del__'
    onerror(os.lstat, path, sys.exc_info())
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxy_65hcd'
AttributeError: 'super' object has no attribute '__del__'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/shutil.py", line 463, in rmtree
Traceback (most recent call last):
  File "/home/jovyan/neuronunit/neuronunit/models/__init__.py", line 193, in __del__
  File "/home/jovyan/neuronunit/neuronunit/models/__init__.py", line 193, in __del__
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxy_65hcd'
    super(LEMSModel,self).__del__()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxy_65hcd'
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpsrqy23l9'
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f427810b668>>
AttributeError: 'super' object has no attribute '__del__'
Exception ignored in: <bound method LEMSModel.__del__ of <neuronunit.models.reduced.ReducedModel object at 0x7f427810b668>>
Exception ignored in: <bound method LEMSModel.__del__ of ```

**Comment by rgerkin** [comment]
I'm not sure if you are referring the __del__ error or the missing file error, but I've just deal with the former in 2dceab5f4cd030e1271e2c2cf9b34153dea7149b

**Comment by rgerkin** [comment]
Fixed with the above-referenced commit.
