### ISSUE TITLE
Fix AIBS module

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#188]
It looks like their API may have changed again, breaking compatibility.  

```
ERROR: test_aibs (neuronunit.unit_test.resource_tests.AIBSTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scidash/neuronunit/neuronunit/unit_test/resource_tests.py", line 45, in test_aibs
    observation = aibs.get_observation(dataset_id,'rheobase')
  File "/home/travis/build/scidash/neuronunit/neuronunit/aibs.py", line 77, in get_observation
    sweep_id = cmd['ephys_features'][0]['rheobase_sweep_id']
KeyError: 'ephys_features'
Stdout:
Getting Rheobase data value for from AIBS dataset 354190013
```

**Comment by rgerkin** [comment]
Fixed in d859aff2e288fae6f8a5bd372828d8a64b12fe55
