### ISSUE TITLE
changes to backends.py results in cryptic error.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#58]
When I revert the below lines back to their previous state this error goes away.
```
            self.__class__.__bases__ = (self._backend.__class__,) + \
                                        self.__class__.__bases__

            # Add all of the backend's methods to the model instance

            #This line breaks the code.
            #self.__class__.__bases__ = tuple(set((self._backend.__class__,) + \
            #                            self.__class__.__bases__))
```
https://github.com/scidash/neuronunit/commit/274dd194209b8158428437ca9a2f598271e4398d
```
<class 'neuronunit.models.reduced.ReducedModel'>
{'injected_square_current': {'amplitude': array(40.0) * pA, 'duration': array(1000.0) * ms, 'delay': array(100.0) * ms}}
{'//izhikevich2007Cell': {'a': '0.03', 'b': '-2e-08'}}
> /home/mnt/neuronunit/tests/exhaustive_search.py(190)f()
-> model.update_run_params(vm.attrs)
(Pdb) c
Traceback (most recent call last):
  File "exhaustive_search.py", line 308, in <module>
    rh_value=searcher(f,rh_param,mean_vm)
  File "exhaustive_search.py", line 220, in searcher
    rh_param[1]=list(futures.map(f,rh_param[1],repeat(vms)))
  File "exhaustive_search.py", line 190, in f
    model.update_run_params(vm.attrs)
  File "/home/mnt/neuronunit/tests/../../neuronunit/capabilities/__init__.py", line 106, in inject_square_current
    raise NotImplementedError()
NotImplementedError
```

**Comment by rgerkin** [comment]
Fixed.
