### ISSUE TITLE
 spikes2widths IndexError: too many indices for array

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#84]
```
Executing test RheobaseTest on model {'vr': '-50.3483250563', 'b': '-4.89873099495e-09', 'C': '9.43648722832e-05', 'k': '0.000747262050596', 'v0': '-71.2276367992', 'c': '-55.6708111127', 'a': '0.169224850835', 'vpeak': '32.4754665645', 'd': '0.0586087052493', 'vt': '-49.9952672311'}... Score is Ratio = 0.00
Executing test InputResistanceTest on model {'vr': '-50.3483250563', 'b': '-4.89873099495e-09', 'C': '9.43648722832e-05', 'k': '0.000747262050596', 'v0': '-71.2276367992', 'c': '-55.6708111127', 'a': '0.169224850835', 'vpeak': '32.4754665645', 'd': '0.0586087052493', 'vt': '-49.9952672311'}... {}
Score is Z = -5.15
Executing test TimeConstantTest on model {'vr': '-50.3483250563', 'b': '-4.89873099495e-09', 'C': '9.43648722832e-05', 'k': '0.000747262050596', 'v0': '-71.2276367992', 'c': '-55.6708111127', 'a': '0.169224850835', 'vpeak': '32.4754665645', 'd': '0.0586087052493', 'vt': '-49.9952672311'}... {}
length of vm_fit 403 offset number 4
/opt/conda/lib/python3.5/site-packages/scipy/optimize/minpack.py:779: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
Score is Z = -1.55
Executing test CapacitanceTest on model {'vr': '-50.3483250563', 'b': '-4.89873099495e-09', 'C': '9.43648722832e-05', 'k': '0.000747262050596', 'v0': '-71.2276367992', 'c': '-55.6708111127', 'a': '0.169224850835', 'vpeak': '32.4754665645', 'd': '0.0586087052493', 'vt': '-49.9952672311'}... {}
length of vm_fit 403 offset number 4
Score is Z = -1.56
Executing test RestingPotentialTest on model {'vr': '-50.3483250563', 'b': '-4.89873099495e-09', 'C': '9.43648722832e-05', 'k': '0.000747262050596', 'v0': '-71.2276367992', 'c': '-55.6708111127', 'a': '0.169224850835', 'vpeak': '32.4754665645', 'd': '0.0586087052493', 'vt': '-49.9952672311'}... {}
Score is Z = -2.20
Executing test InjectedCurrentAPWidthTest on model {'vr': '-50.3483250563', 'b': '-4.89873099495e-09', 'C': '9.43648722832e-05', 'k': '0.000747262050596', 'v0': '-71.2276367992', 'c': '-55.6708111127', 'a': '0.169224850835', 'vpeak': '32.4754665645', 'd': '0.0586087052493', 'vt': '-49.9952672311'}... {}
Traceback (most recent call last):
  File "nsga_parallel.py", line 570, in <module>
    fitnesses.append(evaluate_e(value,vmpop[key]))
  File "nsga_parallel.py", line 216, in evaluate_e
    assert get_neab.suite.judge(model)#passing in model, changes the model
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.8-py3.5.egg/sciunit/__init__.py", line 424, in judge
    stop_on_error,deep_error)
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.8-py3.5.egg/sciunit/__init__.py", line 456, in judge_one
    deep_error=deep_error)
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.8-py3.5.egg/sciunit/__init__.py", line 319, in judge
    raise score.score # An exception.  
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.8-py3.5.egg/sciunit/__init__.py", line 313, in judge
    score = self._judge(model, skip_incapable=skip_incapable)
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.8-py3.5.egg/sciunit/__init__.py", line 258, in _judge
    prediction = self.generate_prediction(model)
  File "/home/jovyan/mnt/neuronunit/neuronunit/optimization/../../neuronunit/tests/__init__.py", line 446, in generate_prediction
    return super(InjectedCurrentAPWidthTest,self).generate_prediction(model)
  File "/home/jovyan/mnt/neuronunit/neuronunit/optimization/../../neuronunit/tests/__init__.py", line 410, in generate_prediction
    widths = model.get_AP_widths()
  File "/home/jovyan/mnt/neuronunit/neuronunit/optimization/../../neuronunit/capabilities/__init__.py", line 83, in get_AP_widths
    widths = spikes2widths(action_potentials)
  File "/home/jovyan/mnt/neuronunit/neuronunit/optimization/../../neuronunit/capabilities/spike_functions.py", line 82, in spikes2widths
    high = s[x_high]
  File "/opt/conda/lib/python3.5/site-packages/quantities/quantity.py", line 364, in __getitem__
    ret = super(Quantity, self).__getitem__(key)
IndexError: too many indices for array
```

**Comment by rgerkin** [comment]
Should be fixed with neo 0.5 changes that have been merged.
