### ISSUE TITLE
AttributeError: 'Quantity' object has no attribute 'sampling_period' 

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#86]
Change to quantities means that `s` in the expression below:

```python 
for s in spike_waveforms:
```
does not have an attribute `sampling_period` Causing the error below:
```
3.329167943001319e-05 V
Traceback (most recent call last):
  File "nsga_parallel.py", line 592, in <module>
    fitnesses.append(evaluate_e(ind,vm))
  File "nsga_parallel.py", line 258, in evaluate_e
    score = get_neab.suite.judge(model,stop_on_error = False, deep_error = True)
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.8-py3.5.egg/sciunit/__init__.py", line 424, in judge
    stop_on_error,deep_error)
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.8-py3.5.egg/sciunit/__init__.py", line 456, in judge_one
    deep_error=deep_error)
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.8-py3.5.egg/sciunit/__init__.py", line 310, in judge
    score = self._judge(model, skip_incapable=skip_incapable)
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.8-py3.5.egg/sciunit/__init__.py", line 258, in _judge
    prediction = self.generate_prediction(model)
  File "/home/jovyan/mnt/neuronunit/neuronunit/optimization/../../neuronunit/tests/__init__.py", line 404, in generate_prediction
    return super(InjectedCurrentAPWidthTest,self).generate_prediction(model)
  File "/home/jovyan/mnt/neuronunit/neuronunit/optimization/../../neuronunit/tests/__init__.py", line 368, in generate_prediction
    widths = model.get_AP_widths()
  File "/home/jovyan/mnt/neuronunit/neuronunit/optimization/../../neuronunit/capabilities/__init__.py", line 83, in get_AP_widths
    widths = spikes2widths(action_potentials)
  File "/home/jovyan/mnt/neuronunit/neuronunit/optimization/../../neuronunit/capabilities/spike_functions.py", line 86, in spikes2widths
AttributeError: 'Quantity' object has no attribute 'sampling_period'
Segmentation fault
```

Its difficult to find where the model in line 347 inherits spike_width tests from capabilities/spike_functions.py however it might be cool if you could get the sampling rate with something like:

widths = model.get_AP_widths()
the neuronunit/tests/__init__.py

```python
    tvec = copy.copy(model.results['t'])
    dt = (tvec[1]-tvec[0])*pq.ms
    import neo
    vm = neo.core.AnalogSignal(np.array(vm).T.squeeze(),
                                   units = pq.mV,
                                   sampling_rate=dt)
```
and make it an attribute of model, that is accessible in the scope of get_AP_widths.

**Comment by rgerkin** [comment]
I encountered this error during the transition to neo 0.5, but the changes I made in the dev branch already should have solved it.  I will check again.

**Comment by russelljjarvis** [comment]
AOK

**Comment by rgerkin** [comment]
I see you merged in my commit that changed `for s in spike_waveforms` to `for i in range(n_spikes)`, among other things.  That should fix the problem, although perhaps you are dealing with new ones.  I am closing this unless this particular problem re-emerges for you.

**Comment by russelljjarvis** [comment]
Yes, I think its fixed.
